version: '3.1'

services:
  db:
    container_name: fichajespi_db
    image: 'linuxserver/mariadb:10.5.13'
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-fichajesroot}
      - TZ=${TZ:-Europe/Madrid}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-db_fichajespi}
      - MYSQL_USER=${MYSQL_USER:-fichajes}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-fichajes}
    volumes:
      - db_data:/config
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u$MYSQL_USER -p$MYSQL_PASSWORD || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: always

  backendserver:
    container_name: fichajespi_back
    build: ./spring-boot_fichajesPi/
    environment:
      - TZ=${TZ:-Europe/Madrid}
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/${MYSQL_DATABASE:-db_fichajespi}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER:-fichajes}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD:-fichajes}
      - CLIENT_URL=${CLIENT_URL:-http://${IP:-localhost}}
      - SPRING_MAIL_HOST=${SPRING_MAIL_HOST:-smtp.mailtrap.io}
      - SPRING_MAIL_PORT=${SPRING_MAIL_PORT:-2525}
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME:-your-user-name}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD:-your-password}
      - JWT_SECRET=${JWT_SECRET:-your-secret-key}
    ports:
      - "8080:8080"
    links:
      - "db"
    depends_on:
      - "db"
    restart: always

  frontend:
    container_name: fichajespi_front
    build:
      context: ./angular_fichajesPi/
      args:
        apiURL: ${API_URL:-http://${IP:-localhost}:8080}
    ports:
      - "80:80"
    environment:
      - TZ=${TZ:-Europe/Madrid}
    restart: always

  phpmyadmin:
    container_name: fichajespi_dbadmin
    image: phpmyadmin
    ports:
      - 81:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=${MYSQL_USER:-fichajes}
      - PMA_PASSWORD=${MYSQL_PASSWORD:-fichajes}
    depends_on:
      - "db"
    restart: always

volumes:
  db_data:
